name: Feature Request
description: Suggest a new feature for ContractKit
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature suggestion! Please describe what you'd like to see.

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New template/blueprint
        - New skill/command
        - Existing template improvement
        - Existing skill improvement
        - Documentation
        - Tooling/CI
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you'd like
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this feature? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds or alternatives?
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to contribute this feature
